package main

import (
	"bytes"
	"github.com/geometrybase/hft-micro/tdigest"
	"github.com/go-echarts/go-echarts/v2/components"
	"io"
	"io/ioutil"
	"os"

	"github.com/go-echarts/go-echarts/v2/charts"
	"github.com/go-echarts/go-echarts/v2/opts"
)

func generateLongData() ([]opts.LineData, []float64) {
	data, _ := ioutil.ReadFile("/Users/chenjilin/Projects/hft-micro/researches/kcuf-bnuf-depth5/configs/longTD")
	td, _ := tdigest.FromBytes(bytes.NewReader(data))
	items := make([]opts.LineData, 0)
	spreads := make([]float64, 0)
	for i := -0.003; i <= 0.003; i += 0.0001 {
		spreads = append(spreads, i)
		items = append(items, opts.LineData{
			Value: td.CDF(i) - td.CDF(i-0.0001),
			Name:  "LONG PDF",
		})
	}
	return items, spreads
}

func generateShortData() ([]opts.LineData, []float64) {
	data, _ := ioutil.ReadFile("/Users/chenjilin/Projects/hft-micro/researches/kcuf-bnuf-depth5/configs/shortTD")
	td, _ := tdigest.FromBytes(bytes.NewReader(data))
	items := make([]opts.LineData, 0)
	spreads := make([]float64, 0)
	for i := -0.003; i <= 0.003; i += 0.0001 {
		spreads = append(spreads, i)
		items = append(items, opts.LineData{
			Value: td.CDF(i) - td.CDF(i-0.0001),
			Name:  "SHORT PDF",
		})
	}
	return items, spreads
}

func main() {
	// create a new bar instance

	longCDF, spreads := generateLongData()
	shortCDF, _ := generateShortData()

	longLine := charts.NewLine()
	longLine.SetGlobalOptions(
		charts.WithTitleOpts(opts.Title{
			Title:    "LONG SPREAD PDF",
			Subtitle: "",
		}))
	longLine.SetXAxis(spreads).AddSeries("LONG PDF", longCDF)

	shortLine := charts.NewLine()
	shortLine.SetGlobalOptions(
		charts.WithTitleOpts(opts.Title{
			Title:    "SHORT SPREAD PDF",
			Subtitle: "",
		}))
	shortLine.SetXAxis(spreads).AddSeries("SHORT PDF", shortCDF)

	//// set some global options like Title/Legend/ToolTip or anything else
	//bar.SetGlobalOptions(charts.WithTitleOpts(opts.Title{
	//	Title:    "My first bar chart generated by go-echarts",
	//	Subtitle: "It's extremely easy to use, right?",
	//}))

	//// Put data into instance
	//bar.SetXAxis([]string{"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"}).
	//	AddSeries("Category A", generateLongData()).
	//	AddSeries("Category B", generateLongData())
	//// Where the magic happens
	f, _ := os.Create("/Users/chenjilin/Projects/hft-micro/researches/kcuf-bnuf-depth5/configs/pdf.html")

	page := components.NewPage()
	page.AddCharts(longLine, shortLine)
	page.Render(io.MultiWriter(f))
}
