// The following directive is necessary to make the package coherent:

// +build ignore

// This program generates contributors.go. It can be invoked by running
// go generate
package main

import (
	"fmt"
	"github.com/geometrybase/hft-micro/logger"
	"os"
	"sort"
	"strings"
	"time"
)

//BTCUSDT,LTCUSDT,ETHUSDT,NEOUSDT,QTUMUSDT,EOSUSDT,ZRXUSDT,OMGUSDT,LRCUSDT,TRXUSDT,KNCUSDT,IOTAUSDT,LINKUSDT,CVCUSDT,ETCUSDT,ZECUSDT,BATUSDT,DASHUSDT,XMRUSDT,ENJUSDT,XRPUSDT,STORJUSDT,BTSUSDT,ADAUSDT,XLMUSDT,WAVESUSDT,ICXUSDT,RLCUSDT,IOSTUSDT,BLZUSDT,ONTUSDT,ZILUSDT,ZENUSDT,THETAUSDT,VETUSDT,RENUSDT,MATICUSDT,ATOMUSDT,FTMUSDT,CHZUSDT,ALGOUSDT,DOGEUSDT,ANKRUSDT,TOMOUSDT,BANDUSDT,XTZUSDT,KAVAUSDT,BCHUSDT,SOLUSDT,HNTUSDT,COMPUSDT,MKRUSDT,SXPUSDT,SNXUSDT,DOTUSDT,RUNEUSDT,BALUSDT,YFIUSDT,SRMUSDT,CRVUSDT,SANDUSDT,OCEANUSDT,LUNAUSDT,RSRUSDT,TRBUSDT,EGLDUSDT,BZRXUSDT,KSMUSDT,SUSHIUSDT,YFIIUSDT,BELUSDT,UNIUSDT,AVAXUSDT,FLMUSDT,ALPHAUSDT,NEARUSDT,AAVEUSDT,FILUSDT,CTKUSDT,AXSUSDT,AKROUSDT,SKLUSDT,GRTUSDT,1INCHUSDT,LITUSDT,RVNUSDT,SFPUSDT,REEFUSDT,DODOUSDT,COTIUSDT,CHRUSDT,ALICEUSDT,HBARUSDT,MANAUSDT,STMXUSDT,UNFIUSDT,XEMUSDT

type Group struct {
	Symbols []string
	Depth   int
	Path    string
}

type Branch struct {
	Symbols  []string
	Depth    int
	Path     string
	Branches []*Branch
}

func HasAllLeaves(b *Branch) bool {
	if len(b.Branches) == 0 {
		return len(b.Symbols) == 1
	} else {
		for _, bb := range b.Branches {
			if !HasAllLeaves(bb) {
				return false
			}
		}
	}
	return true
}

func WalkBranch(b *Branch) {
	if len(b.Symbols) <= 1 {
		//logger.Debugf("%s %s", b.Path, b.Symbols)
		return
	}
	b.Branches = make([]*Branch, 0)
	depth := b.Depth + 1
	symbolsMap := make(map[string][]string)
	for _, symbol := range b.Symbols {
		if _, ok := symbolsMap[symbol[:depth]]; !ok {
			symbolsMap[symbol[:depth]] = []string{symbol}
		} else {
			symbolsMap[symbol[:depth]] = append(symbolsMap[symbol[:depth]], symbol)
		}
	}
	for path, symbols := range symbolsMap {
		b.Branches = append(b.Branches, &Branch{
			Path:    path,
			Symbols: symbols,
			Depth:   depth,
		})
	}
	for _, branch := range b.Branches {
		WalkBranch(branch)
	}
}

func GetDepthOffset(depth int) string {
	offset := "  "
	for i := 0; i < depth; i++ {
		offset += "  "
	}
	return offset
}

func GetBranchSwitchCode(b *Branch, symbols []string) string {
	if len(b.Branches) < 1 {
		//logger.Debugf("%s %s", b.Path, b.Symbols)
		return fmt.Sprintf(
			"%scase '%s':\n%s  return %d\n",
			GetDepthOffset(b.Depth),
			b.Symbols[0][b.Depth-1:b.Depth],
			GetDepthOffset(b.Depth),
			sort.SearchStrings(symbols, b.Symbols[0]),
			//b.Symbols[0],
		)
	} else {
		cases := ""
		for _, b1 := range b.Branches {
			cases += GetBranchSwitchCode(b1, symbols)
		}
		return fmt.Sprintf(
			"%scase '%s':\n%s  switch symbol[%d]{\n%s%sdefault:\n%sreturn -1\n%s}\n",
			GetDepthOffset(b.Depth),
			b.Symbols[0][b.Depth-1:b.Depth],
			GetDepthOffset(b.Depth),
			b.Depth,
			cases,
			GetDepthOffset(b.Depth+1),
			GetDepthOffset(b.Depth+2),
			GetDepthOffset(b.Depth),
		)
	}
}

func main() {

	symbols := []string{
		"BTCUSDT", "LTCUSDT", "ETHUSDT", "NEOUSDT", "QTUMUSDT",
		"EOSUSDT", "ZRXUSDT", "OMGUSDT", "LRCUSDT", "TRXUSDT",
		"KNCUSDT", "IOTAUSDT", "LINKUSDT", "CVCUSDT", "ETCUSDT",
		"ZECUSDT", "BATUSDT", "DASHUSDT", "XMRUSDT", "ENJUSDT",
		"XRPUSDT", "STORJUSDT", "BTSUSDT", "ADAUSDT", "XLMUSDT",
		"WAVESUSDT", "ICXUSDT", "RLCUSDT", "IOSTUSDT", "BLZUSDT",
		"ONTUSDT", "ZILUSDT", "ZENUSDT", "THETAUSDT", "VETUSDT",
		"RENUSDT", "MATICUSDT", "ATOMUSDT", "FTMUSDT", "CHZUSDT",
		"ALGOUSDT", "DOGEUSDT", "ANKRUSDT", "TOMOUSDT", "BANDUSDT",
		"XTZUSDT", "KAVAUSDT", "BCHUSDT", "SOLUSDT", "HNTUSDT",
		"COMPUSDT", "MKRUSDT", "SXPUSDT", "SNXUSDT", "DOTUSDT",
		"RUNEUSDT", "BALUSDT", "YFIUSDT", "SRMUSDT", "CRVUSDT",
		"SANDUSDT", "OCEANUSDT", "LUNAUSDT", "RSRUSDT",
		"TRBUSDT", "EGLDUSDT", "BZRXUSDT", "KSMUSDT", "SUSHIUSDT",
		"YFIIUSDT", "BELUSDT", "UNIUSDT", "AVAXUSDT", "FLMUSDT",
		"ALPHAUSDT", "NEARUSDT", "AAVEUSDT", "FILUSDT", "CTKUSDT",
		"AXSUSDT", "AKROUSDT", "SKLUSDT", "GRTUSDT", "1INCHUSDT",
		"LITUSDT", "RVNUSDT", "SFPUSDT", "REEFUSDT", "DODOUSDT",
		"COTIUSDT", "CHRUSDT", "ALICEUSDT", "HBARUSDT", "MANAUSDT",
		"STMXUSDT", "UNFIUSDT", "XEMUSDT",
	}

	sort.Strings(symbols)

	tree := &Branch{
		Symbols: symbols,
		Depth:   0,
		Path:    "",
	}
	WalkBranch(tree)
	cases := ""
	if len(tree.Branches) == 0 {
		cases += fmt.Sprintf("  case '%s':\n", symbols[0][:1])
		cases += "    return 0\n"
	} else {
		for _, b1 := range tree.Branches {
			cases += GetBranchSwitchCode(b1, symbols)
		}
	}
	codes := "// Code generated by go generate; DO NOT EDIT.\n"
	codes += "package main\n\n"
	codes += fmt.Sprintf("const SYMBOLS_LEN=%d\n", len(symbols))
	codes += fmt.Sprintf("const BUILD_TIME=\"%s\"\n", time.Now().Format(time.RFC3339))
	codes += "const BNBUSDT=\"BNBUSDT\"\n"
	codes += fmt.Sprintf("var SYMBOLS = [SYMBOLS_LEN]string{\"%s\"}\n\n", strings.Join(symbols, `","`))
	codes += "\nfunc GetSymbolIndex(symbol string) int{\n"
	codes += fmt.Sprintf("  switch symbol[0] {\n%s  default:\n    return -1\n  }\n", cases)
	codes += "  return -1\n"
	codes += "}\n"
	f, err := os.Create("symbols.go")
	if err != nil {
		logger.Fatal(err)
	}
	defer f.Close()
	f.Write([]byte(codes))
}
