name: hbcrossswapspot-mt-xf
dryRun: true
proxyAddress: socks5://127.0.0.1:1082
cpuProfile: #/Users/chenjilin/Downloads/hbcrossswapspot-mt.prof
internalInflux:
  address: http://jilinchen.com:18086
  username: hft
  password: hft
  database: test
  measurement: hbcrossswapspot-mt-xf
  batchSize: 10
  saveInterval: 1m0s
externalInflux:
  address: http://jilinchen.com:18086
  username: hft
  password: hft
  database: test
  measurement: accounts
  batchSize: 0
  saveInterval: 1m0s
apiKey: a87ff3b2-3d2xc4v5bu-9b466eb6-33148
apiSecret: e03cdbc6-6fda4263-c5410355-762fc

leverage: 10
loopInterval: 5s
pullInterval: 1m0s

resetUnrealisedPnlInterval: 15m
resetUnrealisedTriggerPct: -0.5
resetCount: 5

balancePositionMaxAge: 3m

pullBarsInterval: 30m
pullBarsRetryInterval: 3s
barsLookback: 180
topQuantile: 0.95
botQuantile: 0.05
tradeCount: 40
makerBandOffset: 0.00222
minimalBandOffset: 0.00222 #0.00222
minimalEnterDelta: 0.00666 #0.00444
maximalExitDelta: -0.00111
topBandScale: 1.0
botBandScale: 1.0

minimalEnterFundingRate: 0.0001
minimalKeepFundingRate: 0.005

orderBookTakerImpact: 500
orderBookMakerImpact: 100
orderBookType: depth5@100ms
orderBookMaxAgeDiff: 250ms
orderBookMaxAge: 500ms
orderBookBatchSize: 30

spreadTimeToLive: 500ms
spreadLookbackMinimalWindow: 3
spreadLookbackDuration: 1s

reBalanceInterval: 1m
insuranceFundingRatio: 0.25
reBalanceMinimalNotional: 20

enterSlippage: 0.03
startValue: 1000
enterFreePct: 0.025
enterMinimalStep: 20
enterTargetFactor: 4
maxUnHedgeValue: 10

orderTimeout: 5s
orderSilent: 5s
orderCancelSilent: 5s
orderMaxCancelCount: 5
enterSilent: 1m

bnbMinSize: 0.1
bnbCheckInterval: 1m
requestInterval: 10s

startValues:
  root: 0
spotSwapPairs:
#  btcusdt: BTC-USDT
#  ethusdt: ETH-USDT
#  ltcusdt: LTC-USDT
#  dogeusdt: DOGE-USDT
#  xrpusdt: XRP-USDT
#  linkusdt: LINK-USDT
#  trxusdt: TRX-USDT
#  dotusdt: DOT-USDT
#  adausdt: ADA-USDT
#  eosusdt: EOS-USDT
#  bchusdt: BCH-USDT
#  bsvusdt: BSV-USDT
#  yfiusdt: YFI-USDT
#  uniusdt: UNI-USDT
  filusdt: FIL-USDT
#  yfiiusdt: YFII-USDT
#  snxusdt: SNX-USDT
#  bnbusdt: BNB-USDT
#  zecusdt: ZEC-USDT
#  dashusdt: DASH-USDT
#  etcusdt: ETC-USDT
#  thetausdt: THETA-USDT
#  ksmusdt: KSM-USDT
#  atomusdt: ATOM-USDT
#  aaveusdt: AAVE-USDT
#  xlmusdt: XLM-USDT
#  sushiusdt: SUSHI-USDT
#  grtusdt: GRT-USDT
#  1inchusdt: 1INCH-USDT
#  crvusdt: CRV-USDT
#  xtzusdt: XTZ-USDT
#  algousdt: ALGO-USDT
#  neousdt: NEO-USDT
#  wavesusdt: WAVES-USDT
#  compusdt: COMP-USDT
#  zilusdt: ZIL-USDT
#  qtumusdt: QTUM-USDT
#  xmrusdt: XMR-USDT
#  omgusdt: OMG-USDT
#  ontusdt: ONT-USDT
#  avaxusdt: AVAX-USDT
#  zksusdt: ZKS-USDT
#  mdxusdt: MDX-USDT
  maticusdt: MATIC-USDT