name: lc01
dryRun: true
reduceOnly: false
resetPrivateHistory: false
internalInflux:
  address: http://192.155.88.24:8086
  username: loochao
  password: Longwayh0me
  database: arbitrage
  measurement: lc01
  batchSize: 10
  saveInterval: 1m0s

xExchange:
  name: dydxV4UsdFuture
  apiKey: dydx1t6yvj6hlfhycjh9axktqe43jsdefkjcfwm326k
  apiSecret: "0xf00147218574463bb5a72408e73cee5920eeeddebc9ccc9e50bae007557373ff"
  apiPassphrase: "wood window protect item truth dumb guard gain butter menu know under cook utility unveil size fan jelly secret result profit father lift quit"
  proxy: "socks5://127.0.0.1:1083"
  leverage: 10
  changeLeverage: false
  pullInterval: 15s

yExchange:
  name: binanceUsdtFutureWithMergedTicker
  apiKey: RX7lQYgeWfe8QYkFn2Eh4IMcEJD5SedemWgx8XgFsE29zC5OoB0vlaSkySi6qH1Q
  apiSecret: UmLz4K1e1lEcFKzsb4HIupi9gf1Of8kCGPGYQHz4Ito5ZStb4UxQruMTnzRUFrGt
  proxy: "socks5://127.0.0.1:1083"
  leverage: 10
  changeLeverage: true
  changePositionMode: true
  changeMarginType: true
  autoAddCommissionDiscountAsset: false
  minCommissionDiscountAssetValue: 30
  marginType: CROSSED
  pullInterval: 15s

streamBatchSize: 30
restartSilent: 3m
restartInterval: 120h
logInterval: 1m
turnoverLookback: 24h
accountMaxAge: 3m

spreadEnterOffset: 0.0024
spreadLeaveOffset: 0.0012
longEnterThreshold: -0.0016
longLeaveThreshold: 0.0012
shortEnterThreshold: 0.0016
shortLeaveThreshold: -0.0012
spreadMiddleMin: -0.01
spreadMiddleMax: 0.01

statsRootPath: /home/clu/workspace/helium/hft-micro-cache
statsSampleInterval: 1s
statsSaveInterval: 15m

timeDeltaLookback: 2h
spreadTDLookback: 72h
spreadTDSubInterval: 15m
spreadTDCompression: 10

spreadShortEnterQuantileTop: 0.95
spreadShortLeaveQuantileBot: 0.20
spreadLongEnterQuantileBot: 0.05
spreadLongLeaveQuantileTop: 0.80

xTimeDeltaOffsetTop: 25ms
xTimeDeltaOffsetBot: -25ms
yTimeDeltaOffsetTop: 25ms
yTimeDeltaOffsetBot: -25ms
xyTimeDeltaOffsetTop: 250ms
xyTimeDeltaOffsetBot: -250ms

fundingRateOpenShortMin: -0.0003
fundingRateOpenLongMax: 0.0003
fundingRateOffsetMin: 0.80
fundingRateOffsetMax: 0.995
xFundingRateEaseFnName: outExpo
yFundingRateEaseFnName: outExpo
fundingRateSilentTime: 1s
xFundingRateWeight: 4.0
yFundingRateWeight: 0.5
xFundingRateInterval: 1h
yFundingRateInterval: 8h
xFundingRateTimeOffset: 0
yFundingRateTimeOffset: 0

tickerMaxRemoteLocalTimeDiff: 5000ms
tickerMaxXYTimeDiff: 150ms
spreadMaxAge: 100ms
spreadLookback: 1s
spreadWalkDelay: 1us

xOrderSilent: 3s
xOrderTimeInForce: IOC
yOrderTimeInForce: IOC
yOrderSilent: 1s
xEnterTimeout: 3m
xEnterSilent: 1s
hedgeRatio: 1.0
hedgeDelay: 0ms
hedgeCheckDuration: 1s
hedgeCheckInterval: 1ms
realisedSpreadLogDelay: 10ms

startValue: 1000
minXFree: 50
minYFree: 50
maxPosValue: 200

enterFreePct: 0.1
bestSizeFactor: 4
enterMinimalStep: 20
enterTargetFactor: 10

enterSlippageLookback: 240h
ySlippageReference: 0.0006
maxSlippage: 0.001

spreadWalkByXTicker: true
spreadWalkByYTicker: true

targetWeightUpdateInterval: 1h
startValues:
  lc01: 1000

xyPairs:
  BTC-USD: BTCUSDT
  ETH-USD: ETHUSDT
  SOL-USD: SOLUSDT
  ZEC-USD: ZECUSDT
  UNI-USD: UNIUSDT
  ADA-USD: ADAUSDT
  AAVE-USD: AAVEUSDT
  BNB-USD: BNBUSDT
  LINK-USD: LINKUSDT
  BLUR-USD: BLURUSDT
  XRP-USD: XRPUSDT
  PAXG-USD: PAXGUSDT
  DOGE-USD: DOGEUSDT
  ZRO-USD: ZROUSDT
  DOT-USD: DOTUSDT
  WIF-USD: WIFUSDT
  INJ-USD: INJUSDT
  ARKM-USD: ARKMUSDT
  SUI-USD: SUIUSDT
  NEAR-USD: NEARUSDT
  HYPE-USD: HYPEUSDT
  SEI-USD: SEIUSDT
  WLD-USD: WLDUSDT
  CHZ-USD: CHZUSDT
  BCH-USD: BCHUSDT
  APT-USD: APTUSDT
  W-USD: WUSDT
  XPL-USD: XPLUSDT
  ONDO-USD: ONDOUSDT
  TAO-USD: TAOUSDT
  LTC-USD: LTCUSDT
  RENDER-USD: RENDERUSDT
  PENDLE-USD: PENDLEUSDT
  AVAX-USD: AVAXUSDT
  PUMP-USD: PUMPUSDT
  ALGO-USD: ALGOUSDT
  ATOM-USD: ATOMUSDT
  ATH-USD: ATHUSDT
  WOO-USD: WOOUSDT
  TRX-USD: TRXUSDT
  ETC-USD: ETCUSDT
  JTO-USD: JTOUSDT
  ICP-USD: ICPUSDT
  STX-USD: STXUSDT
  ORDI-USD: ORDIUSDT
  POL-USD: POLUSDT
  EIGEN-USD: EIGENUSDT
  XMR-USD: XMRUSDT
  STRK-USD: STRKUSDT
  JUP-USD: JUPUSDT
  XLM-USD: XLMUSDT
  ASTER-USD: ASTERUSDT
  ENA-USD: ENAUSDT
  OP-USD: OPUSDT
  MET-USD: METUSDT
  S-USD: SUSDT
  SNX-USD: SNXUSDT
  1INCH-USD: 1INCHUSDT
  DYM-USD: DYMUSDT
  APE-USD: APEUSDT
  MOVE-USD: MOVEUSDT
  ARB-USD: ARBUSDT
  HBAR-USD: HBARUSDT
  CRV-USD: CRVUSDT
  LDO-USD: LDOUSDT
  TIA-USD: TIAUSDT
  WLFI-USD: WLFIUSDT
  PYTH-USD: PYTHUSDT
  FIL-USD: FILUSDT
  TON-USD: TONUSDT
  ETHFI-USD: ETHFIUSDT
  ZEN-USD: ZENUSDT
  AEVO-USD: AEVOUSDT
  PEOPLE-USD: PEOPLEUSDT
  AVNT-USD: AVNTUSDT
  TRUMP-USD: TRUMPUSDT
  PENGU-USD: PENGUUSDT
  ZORA-USD: ZORAUSDT
  AXL-USD: AXLUSDT
  DYDX-USD: DYDXUSDT
  SPX-USD: SPXUSDT
  RUNE-USD: RUNEUSDT
  IMX-USD: IMXUSDT
  USUAL-USD: USUALUSDT
  AXS-USD: AXSUSDT
  MORPHO-USD: MORPHOUSDT
  2Z-USD: 2ZUSDT
  MANA-USD: MANAUSDT
  SYRUP-USD: SYRUPUSDT
  DRIFT-USD: DRIFTUSDT
  ENS-USD: ENSUSDT
  ZK-USD: ZKUSDT
  COMP-USD: COMPUSDT
  GRT-USD: GRTUSDT
  AERO-USD: AEROUSDT
  AKT-USD: AKTUSDT
  ANIME-USD: ANIMEUSDT
  ASTR-USD: ASTRUSDT
  BANANA-USD: BANANAUSDT
  BERA-USD: BERAUSDT
  CAKE-USD: CAKEUSDT
  CVX-USD: CVXUSDT
  DASH-USD: DASHUSDT
  DEGEN-USD: DEGENUSDT
  GOAT-USD: GOATUSDT
  IO-USD: IOUSDT
  IOTA-USD: IOTAUSDT
  IOTX-USD: IOTXUSDT
  IP-USD: IPUSDT
  JASMY-USD: JASMYUSDT
  KAITO-USD: KAITOUSDT
  KAS-USD: KASUSDT
  KOMA-USD: KOMAUSDT
  LINEA-USD: LINEAUSDT

maxPosSizes:
  BTC-USD: 0.002996
  ETH-USD: 0.097375
  SOL-USD: 2.543686
  ZEC-USD: 0.425332
  UNI-USD: 31.637694
  ADA-USD: 416.920861
  AAVE-USD: 1.060445
  BNB-USD: 0.174647
  LINK-USD: 11.690437
  BLUR-USD: 5028.622365
  XRP-USD: 77.402106
  PAXG-USD: 0.021464
  DOGE-USD: 1108.266844
  ZRO-USD: 53.378523
  DOT-USD: 81.844062
  WIF-USD: 281.821692
  INJ-USD: 18.021442
  ARKM-USD: 523.39382
  SUI-USD: 58.380776
  NEAR-USD: 43.243613
  HYPE-USD: 1.439608
  SEI-USD: 967.288764
  WLD-USD: 187.618649
  CHZ-USD: 1270.163422
  BCH-USD: 0.112534
  APT-USD: 58.491522
  W-USD: 3509.449635
  XPL-USD: 440.609976
  ONDO-USD: 193.830294
  TAO-USD: 0.165251
  LTC-USD: 0.96342
  RENDER-USD: 28.30051
  PENDLE-USD: 45.838151
  AVAX-USD: 5.724619
  PUMP-USD: 31177.754168
  ALGO-USD: 473.933649
  ATOM-USD: 30.324115
  ATH-USD: 7697.360465
  WOO-USD: 3062.417114
  TRX-USD: 158.721595
  ETC-USD: 6.343416
  JTO-USD: 189.269493
  ICP-USD: 11.202827
  STX-USD: 116.519106
  ORDI-USD: 11.029974
  POL-USD: 273.237704
  EIGEN-USD: 162.988918
  XMR-USD: 0.075955
  STRK-USD: 742.82534
  JUP-USD: 159.560733
  XLM-USD: 153.577644
  ASTER-USD: 37.79493
  ENA-USD: 312.951005
  OP-USD: 234.789913
  MET-USD: 197.024852
  S-USD: 597.604617
  SNX-USD: 90.917789
  1INCH-USD: 287.781998
  DYM-USD: 1099.608328
  APE-USD: 299.100024
  MOVE-USD: 1405.099751
  ARB-USD: 273.550331
  HBAR-USD: 288.994685
  CRV-USD: 121.088985
  LDO-USD: 79.920623
  TIA-USD: 87.268762
  WLFI-USD: 254.657363
  PYTH-USD: 628.519358
  FIL-USD: 30.685444
  TON-USD: 20.335944
  ETHFI-USD: 56.241285
  ZEN-USD: 4.881831
  AEVO-USD: 1131.406482
  PEOPLE-USD: 4025.450651
  AVNT-USD: 202.85465
  TRUMP-USD: 8.885883
  PENGU-USD: 4051.300582
  ZORA-USD: 1786.990708
  AXL-USD: 569.262965
  DYDX-USD: 260.955442
  SPX-USD: 95.5467
  RUNE-USD: 63.14394
  IMX-USD: 185.478458
  USUAL-USD: 2008.354272
  AXS-USD: 23.158255
  MORPHO-USD: 16.500561
  2Z-USD: 325.045502
  MANA-USD: 291.036088
  SYRUP-USD: 119.670378
  DRIFT-USD: 520.878593
  ENS-USD: 4.545795
  ZK-USD: 1476.95662
  COMP-USD: 1.530591
  GRT-USD: 1063.073996
  AERO-USD: 79.54979
  AKT-USD: 54.220885
  ANIME-USD: 5614.404387
  ASTR-USD: 3502.219707
  BANANA-USD: 7.717493
  BERA-USD: 62.168338
  CAKE-USD: 18.881768
  CVX-USD: 14.768909
  DASH-USD: 0.827698
  DEGEN-USD: 37541.290934
  GOAT-USD: 1442.033711
  IO-USD: 248.79105
  IOTA-USD: 422.644108
  IOTX-USD: 5689.476825
  IP-USD: 52.063649
  JASMY-USD: 4704.577354
  KAITO-USD: 61.034688
  KAS-USD: 800.848815
  KOMA-USD: 4063.561481
  LINEA-USD: 8415.516689

posWeights:
  BTC-USD: 1.000000
  ETH-USD: 1.000000
  SOL-USD: 1.000000
  ZEC-USD: 0.500000
  UNI-USD: 0.500000
  ADA-USD: 0.500000
  AAVE-USD: 0.500000
  BNB-USD: 0.500000
  LINK-USD: 0.500000
  BLUR-USD: 0.500000
  XRP-USD: 0.500000
  PAXG-USD: 0.500000
  DOGE-USD: 0.500000
  ZRO-USD: 0.500000
  DOT-USD: 0.500000
  WIF-USD: 0.300000
  INJ-USD: 0.300000
  ARKM-USD: 0.300000
  SUI-USD: 0.300000
  NEAR-USD: 0.300000
  HYPE-USD: 0.300000
  SEI-USD: 0.300000
  WLD-USD: 0.300000
  CHZ-USD: 0.300000
  BCH-USD: 0.300000
  APT-USD: 0.300000
  W-USD: 0.300000
  XPL-USD: 0.300000
  ONDO-USD: 0.300000
  TAO-USD: 0.300000
  LTC-USD: 0.300000
  RENDER-USD: 0.300000
  PENDLE-USD: 0.300000
  AVAX-USD: 0.300000
  PUMP-USD: 0.300000
  ALGO-USD: 0.300000
  ATOM-USD: 0.300000
  ATH-USD: 0.300000
  WOO-USD: 0.300000
  TRX-USD: 0.300000
  ETC-USD: 0.300000
  JTO-USD: 0.300000
  ICP-USD: 0.200000
  STX-USD: 0.200000
  ORDI-USD: 0.200000
  POL-USD: 0.200000
  EIGEN-USD: 0.200000
  XMR-USD: 0.200000
  STRK-USD: 0.200000
  JUP-USD: 0.200000
  XLM-USD: 0.200000
  ASTER-USD: 0.200000
  ENA-USD: 0.200000
  OP-USD: 0.200000
  MET-USD: 0.200000
  S-USD: 0.200000
  SNX-USD: 0.200000
  1INCH-USD: 0.200000
  DYM-USD: 0.200000
  APE-USD: 0.200000
  MOVE-USD: 0.200000
  ARB-USD: 0.200000
  HBAR-USD: 0.200000
  CRV-USD: 0.200000
  LDO-USD: 0.200000
  TIA-USD: 0.200000
  WLFI-USD: 0.200000
  PYTH-USD: 0.200000
  FIL-USD: 0.200000
  TON-USD: 0.200000
  ETHFI-USD: 0.200000
  ZEN-USD: 0.200000
  AEVO-USD: 0.200000
  PEOPLE-USD: 0.200000
  AVNT-USD: 0.200000
  TRUMP-USD: 0.200000
  PENGU-USD: 0.200000
  ZORA-USD: 0.200000
  AXL-USD: 0.200000
  DYDX-USD: 0.200000
  SPX-USD: 0.200000
  RUNE-USD: 0.200000
  IMX-USD: 0.200000
  USUAL-USD: 0.200000
  AXS-USD: 0.200000
  MORPHO-USD: 0.200000
  2Z-USD: 0.200000
  MANA-USD: 0.200000
  SYRUP-USD: 0.200000
  DRIFT-USD: 0.200000
  ENS-USD: 0.200000
  ZK-USD: 0.200000
  COMP-USD: 0.200000
  GRT-USD: 0.200000
  AERO-USD: 0.200000
  AKT-USD: 0.200000
  ANIME-USD: 0.200000
  ASTR-USD: 0.200000
  BANANA-USD: 0.200000
  BERA-USD: 0.200000
  CAKE-USD: 0.200000
  CVX-USD: 0.200000
  DASH-USD: 0.200000
  DEGEN-USD: 0.200000
  GOAT-USD: 0.200000
  IO-USD: 0.200000
  IOTA-USD: 0.200000
  IOTX-USD: 0.200000
  IP-USD: 0.200000
  JASMY-USD: 0.200000
  KAITO-USD: 0.200000
  KAS-USD: 0.200000
  KOMA-USD: 0.200000
  LINEA-USD: 0.200000
