package dydx_usdfuture

var TickSizes = map[string]float64{
	"UNI-USD":   0.001,
	"CRV-USD":   0.001,
	"YFI-USD":   1,
	"DOGE-USD":  0.0001,
	"COMP-USD":  0.1,
	"LINK-USD":  0.001,
	"AAVE-USD":  0.01,
	"FIL-USD":   0.01,
	"1INCH-USD": 0.001,
	"EOS-USD":   0.001,
	"BTC-USD":   1,
	"XMR-USD":   0.1,
	"MKR-USD":   1,
	"ATOM-USD":  0.01,
	"SOL-USD":   0.001,
	"DOT-USD":   0.01,
	"UMA-USD":   0.01,
	"LTC-USD":   0.1,
	"SNX-USD":   0.01,
	"AVAX-USD":  0.01,
	"MATIC-USD": 0.001,
	"ETH-USD":   0.1,
	"BCH-USD":   0.1,
	"SUSHI-USD": 0.001,
	"ADA-USD":   0.001,
}

var StepSizes = map[string]float64{
	"AAVE-USD":  0.01,
	"1INCH-USD": 1,
	"LTC-USD":   0.01,
	"EOS-USD":   1,
	"SUSHI-USD": 0.1,
	"XMR-USD":   0.01,
	"COMP-USD":  0.01,
	"YFI-USD":   0.0001,
	"ATOM-USD":  0.1,
	"SOL-USD":   0.1,
	"UMA-USD":   0.1,
	"ADA-USD":   1,
	"LINK-USD":  0.1,
	"FIL-USD":   0.1,
	"MATIC-USD": 1,
	"CRV-USD":   1,
	"DOT-USD":   0.1,
	"DOGE-USD":  10,
	"UNI-USD":   0.1,
	"ETH-USD":   0.001,
	"BCH-USD":   0.01,
	"BTC-USD":   0.0001,
	"SNX-USD":   0.1,
	"AVAX-USD":  0.1,
	"MKR-USD":   0.001,
}

var MinSizes = map[string]float64{
	"COMP-USD":  0.1,
	"DOGE-USD":  100,
	"FIL-USD":   1,
	"UNI-USD":   1,
	"MKR-USD":   0.01,
	"CRV-USD":   10,
	"EOS-USD":   10,
	"XMR-USD":   0.1,
	"ETH-USD":   0.01,
	"ATOM-USD":  1,
	"ADA-USD":   10,
	"AAVE-USD":  0.1,
	"1INCH-USD": 10,
	"SNX-USD":   1,
	"MATIC-USD": 10,
	"SOL-USD":   1,
	"BCH-USD":   0.1,
	"YFI-USD":   0.001,
	"LINK-USD":  1,
	"UMA-USD":   1,
	"AVAX-USD":  1,
	"LTC-USD":   0.1,
	"DOT-USD":   1,
	"BTC-USD":   0.001,
	"SUSHI-USD": 1,
}

var TickPrecisions = map[string]int{
	"EOS-USD":   3,
	"UMA-USD":   2,
	"ADA-USD":   3,
	"MKR-USD":   0,
	"SNX-USD":   2,
	"FIL-USD":   2,
	"1INCH-USD": 3,
	"CRV-USD":   3,
	"DOT-USD":   2,
	"SUSHI-USD": 3,
	"XMR-USD":   1,
	"YFI-USD":   0,
	"UNI-USD":   3,
	"ETH-USD":   1,
	"BCH-USD":   1,
	"BTC-USD":   0,
	"COMP-USD":  1,
	"AVAX-USD":  2,
	"MATIC-USD": 3,
	"SOL-USD":   3,
	"LINK-USD":  3,
	"DOGE-USD":  4,
	"AAVE-USD":  2,
	"LTC-USD":   1,
	"ATOM-USD":  2,
}

var StepPrecisions = map[string]int{
	"SNX-USD":   1,
	"1INCH-USD": 0,
	"ATOM-USD":  1,
	"XMR-USD":   2,
	"COMP-USD":  2,
	"ADA-USD":   0,
	"AAVE-USD":  2,
	"CRV-USD":   0,
	"LINK-USD":  1,
	"MATIC-USD": 0,
	"SOL-USD":   1,
	"BCH-USD":   2,
	"DOT-USD":   1,
	"FIL-USD":   1,
	"MKR-USD":   3,
	"YFI-USD":   4,
	"DOGE-USD":  0,
	"AVAX-USD":  1,
	"UNI-USD":   1,
	"EOS-USD":   0,
	"BTC-USD":   4,
	"SUSHI-USD": 1,
	"UMA-USD":   1,
	"ETH-USD":   3,
	"LTC-USD":   2,
}
