// Code generated by go generate; DO NOT EDIT.
package common

var BnSymbols=[]string{"1INCHUSDT","AAVEUSDT","ADAUSDT","AKROUSDT","ALGOUSDT","ALICEUSDT","ALPHAUSDT","ANKRUSDT","ATOMUSDT","AVAXUSDT","AXSUSDT","BALUSDT","BANDUSDT","BATUSDT","BCHUSDT","BELUSDT","BLZUSDT","BTCUSDT","BTSUSDT","BZRXUSDT","CHRUSDT","CHZUSDT","COMPUSDT","COTIUSDT","CRVUSDT","CTKUSDT","CVCUSDT","DASHUSDT","DODOUSDT","DOGEUSDT","DOTUSDT","EGLDUSDT","ENJUSDT","EOSUSDT","ETCUSDT","ETHUSDT","FILUSDT","FLMUSDT","FTMUSDT","GRTUSDT","HBARUSDT","HNTUSDT","ICXUSDT","IOSTUSDT","IOTAUSDT","KAVAUSDT","KNCUSDT","KSMUSDT","LINKUSDT","LITUSDT","LRCUSDT","LTCUSDT","LUNAUSDT","MANAUSDT","MATICUSDT","MKRUSDT","NEARUSDT","NEOUSDT","OCEANUSDT","OMGUSDT","ONTUSDT","QTUMUSDT","REEFUSDT","RENUSDT","RLCUSDT","RSRUSDT","RUNEUSDT","RVNUSDT","SANDUSDT","SFPUSDT","SKLUSDT","SNXUSDT","SOLUSDT","SRMUSDT","STMXUSDT","STORJUSDT","SUSHIUSDT","SXPUSDT","THETAUSDT","TOMOUSDT","TRBUSDT","TRXUSDT","UNFIUSDT","UNIUSDT","VETUSDT","WAVESUSDT","XEMUSDT","XLMUSDT","XMRUSDT","XRPUSDT","XTZUSDT","YFIIUSDT","YFIUSDT","ZECUSDT","ZENUSDT","ZILUSDT","ZRXUSDT"}

func GetSymbolIndex(symbol string) int{
  switch symbol[0] {
    case 'B':
      switch symbol[1]{
      case 'A':
        switch symbol[2]{
        case 'L':
          return 11
        case 'N':
          return 12
        case 'T':
          return 13
        default:
          return -1
      }
      case 'C':
        return 14
      case 'E':
        return 15
      case 'L':
        return 16
      case 'T':
        switch symbol[2]{
        case 'S':
          return 18
        case 'C':
          return 17
        default:
          return -1
      }
      case 'Z':
        return 19
      default:
        return -1
    }
    case 'G':
      return 39
    case 'R':
      switch symbol[1]{
      case 'E':
        switch symbol[2]{
        case 'N':
          return 63
        case 'E':
          return 62
        default:
          return -1
      }
      case 'L':
        return 64
      case 'S':
        return 65
      case 'U':
        return 66
      case 'V':
        return 67
      default:
        return -1
    }
    case 'S':
      switch symbol[1]{
      case 'T':
        switch symbol[2]{
        case 'M':
          return 74
        case 'O':
          return 75
        default:
          return -1
      }
      case 'X':
        return 77
      case 'A':
        return 68
      case 'F':
        return 69
      case 'N':
        return 71
      case 'U':
        return 76
      case 'K':
        return 70
      case 'O':
        return 72
      case 'R':
        return 73
      default:
        return -1
    }
    case 'U':
      switch symbol[1]{
      case 'N':
        switch symbol[2]{
        case 'F':
          return 82
        case 'I':
          return 83
        default:
          return -1
      }
      default:
        return -1
    }
    case 'V':
      return 84
    case 'W':
      return 85
    case 'Z':
      switch symbol[1]{
      case 'E':
        switch symbol[2]{
        case 'C':
          return 93
        case 'N':
          return 94
        default:
          return -1
      }
      case 'I':
        return 95
      case 'R':
        return 96
      default:
        return -1
    }
    case 'A':
      switch symbol[1]{
      case 'A':
        return 1
      case 'D':
        return 2
      case 'K':
        return 3
      case 'L':
        switch symbol[2]{
        case 'G':
          return 4
        case 'I':
          return 5
        case 'P':
          return 6
        default:
          return -1
      }
      case 'N':
        return 7
      case 'T':
        return 8
      case 'V':
        return 9
      case 'X':
        return 10
      default:
        return -1
    }
    case 'E':
      switch symbol[1]{
      case 'G':
        return 31
      case 'N':
        return 32
      case 'O':
        return 33
      case 'T':
        switch symbol[2]{
        case 'C':
          return 34
        case 'H':
          return 35
        default:
          return -1
      }
      default:
        return -1
    }
    case 'F':
      switch symbol[1]{
      case 'I':
        return 36
      case 'L':
        return 37
      case 'T':
        return 38
      default:
        return -1
    }
    case 'I':
      switch symbol[1]{
      case 'C':
        return 42
      case 'O':
        switch symbol[2]{
        case 'S':
          return 43
        case 'T':
          return 44
        default:
          return -1
      }
      default:
        return -1
    }
    case 'M':
      switch symbol[1]{
      case 'A':
        switch symbol[2]{
        case 'N':
          return 53
        case 'T':
          return 54
        default:
          return -1
      }
      case 'K':
        return 55
      default:
        return -1
    }
    case 'Q':
      return 61
    case 'T':
      switch symbol[1]{
      case 'H':
        return 78
      case 'O':
        return 79
      case 'R':
        switch symbol[2]{
        case 'B':
          return 80
        case 'X':
          return 81
        default:
          return -1
      }
      default:
        return -1
    }
    case 'X':
      switch symbol[1]{
      case 'R':
        return 89
      case 'T':
        return 90
      case 'E':
        return 86
      case 'L':
        return 87
      case 'M':
        return 88
      default:
        return -1
    }
    case 'C':
      switch symbol[1]{
      case 'T':
        return 25
      case 'V':
        return 26
      case 'H':
        switch symbol[2]{
        case 'R':
          return 20
        case 'Z':
          return 21
        default:
          return -1
      }
      case 'O':
        switch symbol[2]{
        case 'M':
          return 22
        case 'T':
          return 23
        default:
          return -1
      }
      case 'R':
        return 24
      default:
        return -1
    }
    case 'D':
      switch symbol[1]{
      case 'A':
        return 27
      case 'O':
        switch symbol[2]{
        case 'G':
          return 29
        case 'T':
          return 30
        case 'D':
          return 28
        default:
          return -1
      }
      default:
        return -1
    }
    case 'K':
      switch symbol[1]{
      case 'A':
        return 45
      case 'N':
        return 46
      case 'S':
        return 47
      default:
        return -1
    }
    case '1':
      return 0
    case 'H':
      switch symbol[1]{
      case 'B':
        return 40
      case 'N':
        return 41
      default:
        return -1
    }
    case 'L':
      switch symbol[1]{
      case 'I':
        switch symbol[2]{
        case 'N':
          return 48
        case 'T':
          return 49
        default:
          return -1
      }
      case 'R':
        return 50
      case 'T':
        return 51
      case 'U':
        return 52
      default:
        return -1
    }
    case 'N':
      switch symbol[1]{
      case 'E':
        switch symbol[2]{
        case 'A':
          return 56
        case 'O':
          return 57
        default:
          return -1
      }
      default:
        return -1
    }
    case 'O':
      switch symbol[1]{
      case 'M':
        return 59
      case 'N':
        return 60
      case 'C':
        return 58
      default:
        return -1
    }
    case 'Y':
      switch symbol[1]{
      case 'F':
        switch symbol[2]{
        case 'I':
          switch symbol[3]{
          case 'U':
            return 92
          case 'I':
            return 91
          default:
            return -1
        }
        default:
          return -1
      }
      default:
        return -1
    }
  default:
    return -1
  }
  return -1
}