#!/bin/bash
# Fetch current HTX USDT-M contract info and generate updated limits file
# This replaces the static PriceTicks/ContractSizes maps with current data
# Run from: ~/workspace/helix/hft-micro-dydx/
set -euo pipefail

echo "=== Fetching HTX USDT-M Contract Info ==="

# Fetch contract info from HTX API
RESPONSE=$(curl -s "https://api.hbdm.com/linear-swap-api/v1/swap_contract_info")

# Check if API returned ok
STATUS=$(echo "$RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin).get('status', 'error'))")
if [ "$STATUS" != "ok" ]; then
    echo "ERROR: API returned status=$STATUS"
    echo "$RESPONSE" | python3 -m json.tool
    exit 1
fi

# Count contracts
COUNT=$(echo "$RESPONSE" | python3 -c "import sys, json; print(len(json.load(sys.stdin)['data']))")
echo "Found $COUNT contracts"

# Generate Go source file
python3 << 'PYEOF'
import json
import sys

with open("/dev/stdin" if sys.stdin.isatty() else "/dev/stdin") as f:
    pass

# Re-read from saved response
import subprocess
result = subprocess.run(
    ["curl", "-s", "https://api.hbdm.com/linear-swap-api/v1/swap_contract_info"],
    capture_output=True, text=True
)
data = json.loads(result.stdout)

if data.get("status") != "ok":
    print(f"ERROR: {data}")
    sys.exit(1)

contracts = data["data"]

# Filter to active contracts only
active = [c for c in contracts if c.get("contract_status") == 1]
active.sort(key=lambda c: c["contract_code"])

print(f"Active contracts: {len(active)} / {len(contracts)} total")

# Generate PriceTicks map
lines_ticks = []
lines_sizes = []
for c in active:
    symbol = c["contract_code"]
    tick = c["price_tick"]
    size = c["contract_size"]
    lines_ticks.append(f'\t"{symbol}": {tick},')
    lines_sizes.append(f'\t"{symbol}": {size},')

go_source = f"""package huobi_usdtfuture

// AUTO-GENERATED by setup-htx-dynamic-contracts.sh
// Generated: {subprocess.run(["date", "-u", "+%Y-%m-%dT%H:%M:%SZ"], capture_output=True, text=True).stdout.strip()}
// Source: https://api.hbdm.com/linear-swap-api/v1/swap_contract_info
// Active contracts: {len(active)}

var PriceTicks = map[string]float64{{
{chr(10).join(lines_ticks)}
}}

var ContractSizes = map[string]float64{{
{chr(10).join(lines_sizes)}
}}
"""

output_file = "huobi-usdtfuture/hbuf-limits.go"
with open(output_file, "w") as f:
    f.write(go_source)

print(f"Written to {output_file}")
print(f"  PriceTicks: {len(lines_ticks)} entries")
print(f"  ContractSizes: {len(lines_sizes)} entries")
PYEOF

echo ""
echo "Done. Review the generated file:"
echo "  cat huobi-usdtfuture/hbuf-limits.go | head -20"
echo ""
echo "To see new symbols not in the old file:"
echo "  diff <(grep -oP '\"[A-Z]+-USDT\"' huobi-usdtfuture.bak.*/hbuf-limits.go | sort -u) \\"
echo "       <(grep -oP '\"[A-Z]+-USDT\"' huobi-usdtfuture/hbuf-limits.go | sort -u)"
