name: bnswap-okspot-delta-ff03-gb
dryRun: true
proxyAddress: socks5://127.0.0.1:1080
internalInflux:
  address: http://hehe.jilinchen.com:7003
  username: hft
  password: hft
  database: test
  measurement: bnswap-okspot-delta-ff03-gb
  batchSize: 10
  saveInterval: 1m0s
externalInflux:
  address: http://hehe.jilinchen.com:7003
  username: hft
  password: hft
  database: test
  measurement: accounts
  batchSize: 0
  saveInterval: 1m0s
marginType: CROSSED
bnApiKey: yuJSE8iKP1G08GJhaJ1MKMVGwmWkTrGmAhQ8tK84wVHd3wDWhcvnuT9xyxl0EZcN
bnApiSecret: Qg8SHiElH1zTFLYGpwe7rPRSpibKYR1WaC6vDhVTCjo10VLSCps5XGaYhlhBjI3R
okApiKey: 297624eb-1abc-4c45-a13a-250a757bac1d
okApiSecret: 9589D50C9D0A478C193BEFEBB1912B63
okPassphrase: maodaye

okApiUrl: https://www.okex.com
okWsUrl: wss://real.okex.com:8443/ws/v3

okApiUrl2: https://aws.okex.com
okWsUrl2: wss://awspush.okex.com:8443/ws/v3

quoteAsset: USDT
leverage: 10
changeLeverage: false
loopInterval: 100ms
pullInterval: 1m0s

resetUnrealisedPnlInterval: 15m
resetUnrealisedTriggerPct: -0.5
resetCount: 5

pullBarsInterval: 15m
pullBarsRetryInterval: 3s
barsLookback: 960
topQuantile: 0.95
botQuantile: 0.05
minimalBandOffset: 0.00222
minimalEnterDelta: 0.00444
maximalExitDelta: 0.000555
topBandScale: 1.0
botBandScale: 1.0
tradeCount: 10

minimalEnterFundingRate: 0.000555
minimalKeepFundingRate: 0.00444

minimalDeltaWindow: 3
minimalOrderBookValue: 20000
orderBookType: depth5@100ms
swapSpotTimeDeltaTolerance: 2500ms
systemTimeDeltaTolerance: 5000ms
deltaLookback: 15s

reBalanceInterval: 1m
insuranceFundingRatio: 0.25
reBalanceMinimalNotional: 20

entrySlippage: 0.05
startValue: 1018
entryStep: 20
entryTarget: 200

orderTimeout: 15s
orderSilent: 5s
entrySilent: 5m

symbols:
  - BTCUSDT
  - ETHUSDT
# - BATUSDT
# - SRMUSDT
# - DOTUSDT
# - BANDUSDT
# - RENUSDT
# - YFIUSDT
# - TRBUSDT
# - YFIIUSDT
# - RSRUSDT
# - SUSHIUSDT
# - KSMUSDT
# - UNIUSDT
# - AVAXUSDT
# - SOLUSDT
# - EGLDUSDT
# - AAVEUSDT
# - FILUSDT
# - NEARUSDT
# - GRTUSDT
# - 1INCHUSDT
# - BCHUSDT
# - DOGEUSDT
# - ADAUSDT
# - ALGOUSDT
# - ATOMUSDT
# - BALUSDT
# - COMPUSDT
# - CRVUSDT
# - FLMUSDT
# - FTMUSDT
# - SNXUSDT
# - WAVESUSDT
# - XTZUSDT
# - ZILUSDT
# - DASHUSDT
# - LRCUSDT
# - XRPUSDT
# - ZECUSDT
# - NEOUSDT
# - QTUMUSDT
# - IOTAUSDT
# - LTCUSDT
# - ETCUSDT
# - EOSUSDT
# - OMGUSDT
# - STORJUSDT
# - LINKUSDT
# - ZRXUSDT
# - CVCUSDT
# - KNCUSDT
# - ICXUSDT
# - TRXUSDT
# - XMRUSDT
# - XLMUSDT
# - IOSTUSDT
# - THETAUSDT
# - MKRUSDT
# - ZENUSDT
# - ONTUSDT
