name: hbcrossswapbnswap-tt-gb-ff01
dryRun: false
proxyAddress: socks5://127.0.0.1:1082
cpuProfile: #/Users/chenjilin/Downloads/hbcrossswapspot-mt.prof
internalInflux:
  address: http://tigger.jilinchen.com:18086
  username: hft
  password: hft
  database: hft
  measurement: hbcrossswapbnswap-tt-gb-ff01
  batchSize: 0
  saveInterval: 1m0s
externalInflux:
  address: http://hehe.jilinchen.com:7003
  username: hft
  password: hft
  database: fund
  measurement: accounts
  batchSize: 0
  saveInterval: 1m0s

hbApiKey: d145d14e-c28e8b45-db057916-b1rkuf4drg
hbApiSecret: 9a4e9695-2233be75-aa0f8d39-a8de7
bnApiKey: ksu8ZMYNnhIXbq0KQtEczuZxMQH5eoRAnJGDBGj6BzlMVtvGpQccIN8kmzU4bE52
bnApiSecret: ZEEI4X5FJ2CoPNwjE05UoJafVl0LM0HtUWIdhxaROvi9StKyihaIZMNEh06JS004

leverage: 3
changeLeverage: false
marginType: CROSSED
loopInterval: 5s
pullInterval: 1m0s
logInterval: 1m

balancePositionMaxAge: 3m

pullBarsInterval: 30m
pullBarsRetryInterval: 3s
barsLookback: 180
topQuantile: 0.55
botQuantile: 0.45
makerBandOffset: 0.000222
minimalBandOffset: 0.000222 #0.00222
minimalEnterDelta: 0.000666 #0.00444
maximalExitDelta: -0.000111
topBandScale: 0.618
botBandScale: 0.618

minimalEnterFundingRate: 0.0001
minimalKeepFundingRate: 0.004

orderBookImpact: 500
orderBookMaxAgeDiff: 250ms
orderBookMaxAge: 500ms
orderBookBatchSize: 30

spreadTimeToLive: 500ms
spreadLookbackMinimalWindow: 3
spreadLookbackDuration: 1s

enterSlippage: 0.03
startValue: 1000
enterFreePct: 0.025
enterMinimalStep: 20
enterTargetFactor: 4
maxUnHedgeValue: 30
startValues:
  root: 0

orderTimeout: 5s
orderSilent: 5s
orderCancelSilent: 5s
orderMaxCancelCount: 5
enterSilent: 10m
restartSilent: 10m

requestInterval: 10s
makerTakerSymbolsMap:
#  BTC-USDT: BTCUSDT
#  ETH-USDT: ETHUSDT
#  LTC-USDT: LTCUSDT
#  DOGE-USDT: DOGEUSDT
#  XRP-USDT: XRPUSDT
#  LINK-USDT: LINKUSDT
#  TRX-USDT: TRXUSDT
#  DOT-USDT: DOTUSDT
#  ADA-USDT: ADAUSDT
#  EOS-USDT: EOSUSDT
#  BCH-USDT: BCHUSDT
#  YFI-USDT: YFIUSDT
#  UNI-USDT: UNIUSDT
  FIL-USDT: FILUSDT
#  YFII-USDT: YFIIUSDT
#  SNX-USDT: SNXUSDT
#  BNB-USDT: BNBUSDT
#  ZEC-USDT: ZECUSDT
#  DASH-USDT: DASHUSDT
#  ETC-USDT: ETCUSDT
#  THETA-USDT: THETAUSDT
#  KSM-USDT: KSMUSDT
#  ATOM-USDT: ATOMUSDT
#  AAVE-USDT: AAVEUSDT
#  XLM-USDT: XLMUSDT
#  SUSHI-USDT: SUSHIUSDT
#  GRT-USDT: GRTUSDT
#  1INCH-USDT: 1INCHUSDT
#  CRV-USDT: CRVUSDT
#  XTZ-USDT: XTZUSDT
#  ALGO-USDT: ALGOUSDT
#  NEO-USDT: NEOUSDT
#  WAVES-USDT: WAVEUSDT
#  COMP-USDT: COMPUSDT
#  ZIL-USDT: ZILUSDT
#  QTUM-USDT: QTUMUSDT
#  XMR-USDT: XMRUSDT
#  OMG-USDT: OMGUSDT
#  ONT-USDT: ONTUSDT
#  AVAX-USDT: AVAXUSDT
#  MATIC-USDT: MATICUSDT